{% set name = "LimeSuite" %}
{% set version = "23.11.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/myriadrf/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fd8a448b92bc5ee4012f0ba58785f3c7e0a4d342b24e26275318802dfe00eb33
  patches:
    - 0001-Modify-build-system-to-use-system-glew-instead-of-th.patch
    - 0002-ConnectionFX3-Allow-choice-between-libusb-and-CyAPI-.patch
    - 0003-Fix-414-missing-chrono-headers-include-for-MSVC.patch
    - 0004-Add-more-missing-MSVC-chrono-include.patch

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - glew
    - libusb
    # required for OpenGL support
    # See https://conda-forge.org/docs/maintainer/knowledge_base/#libgl
    - libgl-devel  # [linux]
    - soapysdr
    - wxwidgets

outputs:
  - name: liblimesuite
    script: install.sh  # [unix]
    script: install.bat  # [not unix]
    build:
      # instructions for manually linking udev rules
      post-link: post-link  # [linux]
      run_exports:
        - {{ pin_subpackage('liblimesuite', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - libusb
    test:
      commands:
        # verify that executables can be run
        - LimeUtil --info

        # check that all the device connections we want are reported
        - LimeUtil --info | grep FT601  # [not win]
        - LimeUtil --info | grep FX3  # [not win]
        - LimeUtil --info | grep PCIEXillybus  # [not win]
        - LimeUtil --info | findstr /l FT601  # [win]
        - LimeUtil --info | findstr /l FX3  # [win]
        - LimeUtil --info | findstr /l PCIEXillybus  # [win]

        # verify that headers get installed
        - test -f $PREFIX/include/lime/LimeSuite.h  # [not win]
        - if not exist %PREFIX%\\Library\\include\\lime\\LimeSuite.h exit 1  # [win]

        # verify that libraries get installed
        - test -f $PREFIX/lib/libLimeSuite${SHLIB_EXT}  # [not win]
        - if not exist %PREFIX%\\Library\\bin\\LimeSuite.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\LimeSuite.lib exit 1  # [win]

        # verify that udev rule gets installed
        - test -f $PREFIX/lib/udev/rules.d/64-limesuite.rules  # [linux]
  - name: soapysdr-module-lms7
    script: install.sh  # [unix]
    script: install.bat  # [not unix]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - {{ pin_subpackage('liblimesuite', exact=True) }}
        - soapysdr
      run:
        - {{ pin_subpackage('liblimesuite', exact=True) }}
    test:
      commands:
        # verify that libraries get installed
        - test -f $PREFIX/lib/SoapySDR/modules{{ soapysdr }}/libLMS7Support.so  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\SoapySDR\\modules{{ soapysdr }}\\LMS7Support.dll exit 1  # [win]

        # show info to see if module is detected
        - SoapySDRUtil --info
  - name: limesuite
    script: install.sh  # [unix]
    script: install.bat  # [not unix]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - glew
        - {{ pin_subpackage('liblimesuite', exact=True) }}
        - libgl-devel  # [linux]
        - {{ pin_subpackage('soapysdr-module-lms7', exact=True) }}
        - wxwidgets
      run:
        - {{ pin_subpackage('liblimesuite', exact=True) }}
        - {{ pin_subpackage('soapysdr-module-lms7', exact=True) }}
    test:
      commands:
        # verify that GUI executables get installed
        - test -f $PREFIX/bin/LimeSuiteGUI  # [not win]
        - if not exist %PREFIX%\\Library\\bin\\LimeSuiteGUI.exe exit 1  # [win]

        # verify limesuite dependencies
        - LimeUtil --info

        # show info to see if module is detected
        - SoapySDRUtil --info

about:
  home: http://wiki.myriadrf.org/Lime_Suite
  license: Apache-2.0 AND MIT AND BSD-3-Clause
  license_file:
    - COPYING
    - external/cpp-feather-ini-parser/LICENSE
    - external/kissFFT/COPYING
    - LICENSE_FTD3XX  # [win]
  summary: Driver and GUI for LMS7002M-based (Lime) SDR platforms
  description: |
    Lime Suite is a collection of software supporting several hardware
    platforms including the LimeSDR, drivers for the LMS7002M transceiver
    RFIC, and other tools for developing with LMS7-based hardware.
    Installing the Lime Suite enables many SDR applications such as GQRX
    to work with supported hardware through the bundled SoapySDR support
    module.

    The `liblimesuite` package contains the main library that other
    packages should develop against. The `soapysdr-module-lms7` package
    contains the Soapy SDR module that supports Lime devices. The
    `limesuite` package provides the entire software suite, depending
    on the previous packages and also providing GUI tools.

    For Windows users of `liblimesuite` with a LimeSDR (not mini!) device,
    this package uses libusb to communicate over USB instead of the standard
    CyUSB library which is not open source. If you have used your LimeSDR
    with another software package, you will have to switch USB drivers to
    one compatible with WinUSB/libusb by installing the WinUSB driver with
    Zadig (https://zadig.akeo.ie/) and selecting your Lime device.

    For Linux users of `liblimesuite`, you will likely want to link the
    provided udev rule into your system installation in order for the
    hardware to have the correct permissions:

        sudo ln -s $CONDA_PREFIX/lib/udev/rules.d/64-limesuite.rules /etc/udev/rules.d/
        sudo udevadm control --reload
        sudo udevadm trigger
  doc_url: https://wiki.myriadrf.org/Lime_Suite
  dev_url: https://github.com/myriadrf/LimeSuite

extra:
  feedstock-name: limesuite
  recipe-maintainers:
    - ryanvolz
